#!/bin/sh
set -e

case "$1" in
  configure)
    adduser --quiet --system --no-create-home \
      --home /var/lib/carbon-c-relay \
      --group \
      carbon-c-relay
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
